-- 创建数据库
CREATE DATABASE `铭中注定2.5`;
USE `铭中注定2.5`;

-- 创建用户信息表
CREATE TABLE 用户信息 (
    用户ID INT PRIMARY KEY AUTO_INCREMENT,
    手机号 VARCHAR(20) NOT NULL,
    密码 VARCHAR(100) NOT NULL,
    头像 VARCHAR(255),
    真实姓名 VARCHAR(50),
    昵称 VARCHAR(50),
    出生日期 DATE,
    性别 VARCHAR(10),
    所在地区 VARCHAR(100),
    角色 ENUM('个体用户', '管理员') NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    更新时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建用户银行账户表
CREATE TABLE 用户银行账户 (
    卡号 VARCHAR(50) PRIMARY KEY,
    用户ID INT NOT NULL,
    银行名称 VARCHAR(100) NOT NULL,
    有效期 DATE NOT NULL,
    安全码 VARCHAR(10) NOT NULL,
    余额 DECIMAL(10,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    更新时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (用户ID) REFERENCES 用户信息(用户ID)
);

-- 创建交易信息表
CREATE TABLE 交易信息 (
    交易ID INT AUTO_INCREMENT PRIMARY KEY,
    转出卡号 VARCHAR(50) NOT NULL,
    转入卡号 VARCHAR(50) NOT NULL,
    交易金额 DECIMAL(10,2) NOT NULL,
    交易类型 ENUM('购物', '服务', '餐饮', '交通', '转账', '黄金', '股票', '基金', '其他') NOT NULL,
    备注 TEXT,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (转出卡号) REFERENCES 用户银行账户(卡号),
    FOREIGN KEY (转入卡号) REFERENCES 用户银行账户(卡号),
    UNIQUE KEY (转出卡号, 转入卡号, 创建时间)
);

-- 创建股票信息表
CREATE TABLE 股票信息 (
    股票ID INT PRIMARY KEY AUTO_INCREMENT,
    股票名称 VARCHAR(100) NOT NULL,
    初始价格 DECIMAL(10,2) NOT NULL,
    当前价格 DECIMAL(10,2) NOT NULL,
    上次查询价格 DECIMAL(10,2) NOT NULL,
    涨跌幅 DECIMAL(5,2) NOT NULL,
    最大回撤 DECIMAL(5,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    更新时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建股票历史价格表
CREATE TABLE 股票历史价格 (
    股票ID INT NOT NULL,
    日期 DATE NOT NULL,
    开盘价 DECIMAL(10,2) NOT NULL,
    收盘价 DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (股票ID, 日期),
    FOREIGN KEY (股票ID) REFERENCES 股票信息(股票ID)
);

-- 创建基金信息表
CREATE TABLE 基金信息 (
    基金ID INT PRIMARY KEY AUTO_INCREMENT,
    基金名称 VARCHAR(100) NOT NULL,
    初始价格 DECIMAL(10,2) NOT NULL,
    当前价格 DECIMAL(10,2) NOT NULL,
    涨跌幅 DECIMAL(5,2) NOT NULL,
    最大回撤 DECIMAL(5,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    更新时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 创建黄金价格表
CREATE TABLE 黄金价格 (
    黄金价格ID INT PRIMARY KEY AUTO_INCREMENT,
    价格 DECIMAL(10,2) NOT NULL,
    品牌 VARCHAR(100) NOT NULL,
    记录时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建用户理财偏好表
CREATE TABLE 用户理财偏好 (
    偏好ID INT AUTO_INCREMENT PRIMARY KEY,
    用户ID INT NOT NULL,
    风险承受能力 ENUM('C1', 'C2', 'C3', 'C4', 'C5') NOT NULL,
    预期收益 DECIMAL(5,2) NOT NULL,
    理财金额 DECIMAL(10,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (用户ID) REFERENCES 用户信息(用户ID)
);

-- 创建用户基金持有表
CREATE TABLE 用户基金持有 (
    用户ID INT NOT NULL,
    基金ID INT NOT NULL,
    持有数量 DECIMAL(10,2) NOT NULL,
    成交单价 DECIMAL(10,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (用户ID, 基金ID, 创建时间),
    FOREIGN KEY (用户ID) REFERENCES 用户信息(用户ID),
    FOREIGN KEY (基金ID) REFERENCES 基金信息(基金ID)
);

-- 创建用户股票持有表
CREATE TABLE 用户股票持有 (
    用户ID INT NOT NULL,
    股票ID INT NOT NULL,
    持有数量 DECIMAL(10,2) NOT NULL,
    成交单价 DECIMAL(10,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (用户ID, 股票ID, 创建时间),
    FOREIGN KEY (用户ID) REFERENCES 用户信息(用户ID),
    FOREIGN KEY (股票ID) REFERENCES 股票信息(股票ID)
);

-- 创建用户黄金持有表
CREATE TABLE 用户黄金持有 (
    用户ID INT NOT NULL,
    黄金价格ID INT NOT NULL,
    持有数量 DECIMAL(10,2) NOT NULL,
    持有成本 DECIMAL(10,2) NOT NULL,
    创建时间 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (用户ID, 黄金价格ID, 创建时间),
    FOREIGN KEY (用户ID) REFERENCES 用户信息(用户ID),
    FOREIGN KEY (黄金价格ID) REFERENCES 黄金价格(黄金价格ID)
);
